// angular/src/app/task/task.component.ts
import { Component, OnInit, Input } from '@angular/core';
import {Task} from '../classes/task';
import {ToastConnectorService} from '../services/toast-connector/toast-connector.service';
import {StoreService} from '../services/store/store.service';


@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.css']
})

export class TaskComponent{
  @Input() task: Task;
  @Input() index: Number;

  async deleteTask() {
    if (await confirm(`do you really want to remove the task '${this.task.name}'?`)) {
      this.store.deleteTask(this.index);
    }
  }

  toggled() {
    console.log('Sending toast message');
    this.toastConnector.showMessage(`Task '${this.task.name}' now marked as ${!this.task.done ? 'done' : 'not done'}`);
    this.store.toggleTask(this.index);
  }

  constructor(private toastConnector: ToastConnectorService,
              private store: StoreService) { }
}

<div class="task">
  <h3>{{task.name}}</h3>
  <input type="checkbox" [(checked)]="task.done" (click)="toggled()">
  <div class="delete badge" (click)="deleteTask()">
    <b>✖</b>
  </div>
</div>

// react-todo/src/components/Task/Task.js
import React, {Component} from 'react'
import './Task.css'
import {removeTask, toggleTask} from '../../store/actions';
import {connect} from 'react-redux'


class Task extends Component {
    constructor(props) {
        super(props);
        this.state = {name: props.name, done: props.done}
    }

    render() {
        return (
            <div className={'Task'}>
                <h3>{this.state.name}</h3>
                <div className={'delete badge'} onClick={() => this.props.removeTask(this.state.name, this.props.id)}>
                    <b>✖</b>
                </div>
                <input type={'checkbox'} checked={this.props.done}
                       onChange={() => this.props.toggleDone(this.props.id)}/>
            </div>
        )
    }
}


const mapDispatchToProps = (dispatch) => {
    return {
        async removeTask(name, id) {
            if (await confirm(`do you really want to remove the task '${name}'?`)) { //eslint-disable-line no-restricted-globals
                dispatch(removeTask(id))
            }
        },
        toggleDone(id) {
            dispatch(toggleTask(id))
        }
    }
};


export default connect(null, mapDispatchToProps)(Task);
